### ISSUE TITLE
Multiple forms on same page

### ISSUE THREAD

**Issue by carine-namshi** [amail/Verimail.js#8]
Thanks in advance for reading.

If I have multiple forms on the same page and want to avoid calling verimail() multiple times and using IDs is there a way I can do this?

E.g. something along these lines?

```
$("input[type='email']").each().verimail({
    denyTempEmailDomains: true,
    messageElement: $(this).find('p.status-message')
});
```

**Comment by rorheden** [comment]
There is currently no built-in support for this. Do you have a specific case in which this logic is valid?
